// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_starter_kit/test/helper/helper_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:connectivity_plus/connectivity_plus.dart' as _i28;
import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart'
    as _i29;
import 'package:device_info_plus/device_info_plus.dart' as _i39;
import 'package:device_info_plus/src/model/android_device_info.dart' as _i15;
import 'package:device_info_plus/src/model/ios_device_info.dart' as _i14;
import 'package:device_info_plus/src/model/linux_device_info.dart' as _i16;
import 'package:device_info_plus/src/model/macos_device_info.dart' as _i18;
import 'package:device_info_plus/src/model/web_browser_info.dart' as _i17;
import 'package:device_info_plus/src/model/windows_device_info.dart' as _i19;
import 'package:device_info_plus_platform_interface/model/base_device_info.dart'
    as _i20;
import 'package:dio/src/adapter.dart' as _i4;
import 'package:dio/src/cancel_token.dart' as _i24;
import 'package:dio/src/dio.dart' as _i7;
import 'package:dio/src/dio_exception.dart' as _i30;
import 'package:dio/src/dio_mixin.dart' as _i3;
import 'package:dio/src/options.dart' as _i2;
import 'package:dio/src/response.dart' as _i6;
import 'package:dio/src/transformer.dart' as _i5;
import 'package:flutter/foundation.dart' as _i34;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i12;
import 'package:flutter_starter_kit/core/infrastructure/data/network/api_client.dart'
    as _i32;
import 'package:flutter_starter_kit/core/infrastructure/data/network/api_endpoint.dart'
    as _i21;
import 'package:flutter_starter_kit/core/infrastructure/data/network/network_connectivity.dart'
    as _i33;
import 'package:flutter_starter_kit/core/infrastructure/data/storage/secure_storage_service.dart'
    as _i36;
import 'package:flutter_starter_kit/core/infrastructure/data/storage/storage_service.dart'
    as _i35;
import 'package:flutter_starter_kit/core/infrastructure/domain/entities/no_params.dart'
    as _i52;
import 'package:flutter_starter_kit/core/utils/device_services.dart' as _i41;
import 'package:flutter_starter_kit/core/utils/platform_checker.dart' as _i40;
import 'package:flutter_starter_kit/features/auth/data/datasources/auth_local_datasource.dart'
    as _i45;
import 'package:flutter_starter_kit/features/auth/data/datasources/auth_remote_datasource.dart'
    as _i46;
import 'package:flutter_starter_kit/features/auth/data/models/requests/login_request.dart'
    as _i43;
import 'package:flutter_starter_kit/features/auth/data/models/requests/register_request.dart'
    as _i44;
import 'package:flutter_starter_kit/features/auth/data/models/responses/login_response.dart'
    as _i22;
import 'package:flutter_starter_kit/features/auth/data/models/user.dart'
    as _i31;
import 'package:flutter_starter_kit/features/auth/data/network/auth_endpoints.dart'
    as _i42;
import 'package:flutter_starter_kit/features/auth/domain/entities/login_credentials.dart'
    as _i47;
import 'package:flutter_starter_kit/features/auth/domain/entities/register_credentials.dart'
    as _i48;
import 'package:flutter_starter_kit/features/auth/domain/entities/user.dart'
    as _i10;
import 'package:flutter_starter_kit/features/auth/domain/repositories/auth_repository.dart'
    as _i23;
import 'package:flutter_starter_kit/features/auth/domain/usecases/delete_account_usecase.dart'
    as _i53;
import 'package:flutter_starter_kit/features/auth/domain/usecases/get_authenticated_user_usecase.dart'
    as _i54;
import 'package:flutter_starter_kit/features/auth/domain/usecases/login_usecase.dart'
    as _i49;
import 'package:flutter_starter_kit/features/auth/domain/usecases/logout_usecase.dart'
    as _i51;
import 'package:flutter_starter_kit/features/auth/domain/usecases/register_usecase.dart'
    as _i50;
import 'package:flutter_starter_kit/features/environments_dev/data/datasources/environment_local_data_source.dart'
    as _i55;
import 'package:flutter_starter_kit/features/environments_dev/data/models/auth_config.dart'
    as _i13;
import 'package:flutter_starter_kit/features/environments_dev/data/models/base_url_config.dart'
    as _i38;
import 'package:flutter_starter_kit/features/environments_dev/data/storage/environment_config_service.dart'
    as _i37;
import 'package:flutter_starter_kit/features/environments_dev/domain/entities/api_config.dart'
    as _i9;
import 'package:flutter_starter_kit/features/environments_dev/domain/entities/base_url_config.dart'
    as _i8;
import 'package:flutter_starter_kit/features/environments_dev/domain/entities/base_url_type.dart'
    as _i27;
import 'package:flutter_starter_kit/features/environments_dev/domain/entities/environment.dart'
    as _i26;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i25;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBaseOptions_0 extends _i1.SmartFake implements _i2.BaseOptions {
  _FakeBaseOptions_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInterceptors_1 extends _i1.SmartFake implements _i3.Interceptors {
  _FakeInterceptors_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpClientAdapter_2 extends _i1.SmartFake
    implements _i4.HttpClientAdapter {
  _FakeHttpClientAdapter_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransformer_3 extends _i1.SmartFake implements _i5.Transformer {
  _FakeTransformer_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_4<T1> extends _i1.SmartFake implements _i6.Response<T1> {
  _FakeResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDio_5 extends _i1.SmartFake implements _i7.Dio {
  _FakeDio_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseUrlConfig_6 extends _i1.SmartFake implements _i8.BaseUrlConfig {
  _FakeBaseUrlConfig_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAPIConfig_7 extends _i1.SmartFake implements _i9.APIConfig {
  _FakeAPIConfig_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInterceptorState_8<T> extends _i1.SmartFake
    implements _i3.InterceptorState<T> {
  _FakeInterceptorState_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_9 extends _i1.SmartFake implements _i10.User {
  _FakeUser_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_10<T> extends _i1.SmartFake implements _i11.Future<T> {
  _FakeFuture_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIOSOptions_11 extends _i1.SmartFake implements _i12.IOSOptions {
  _FakeIOSOptions_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAndroidOptions_12 extends _i1.SmartFake
    implements _i12.AndroidOptions {
  _FakeAndroidOptions_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLinuxOptions_13 extends _i1.SmartFake implements _i12.LinuxOptions {
  _FakeLinuxOptions_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWindowsOptions_14 extends _i1.SmartFake
    implements _i12.WindowsOptions {
  _FakeWindowsOptions_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebOptions_15 extends _i1.SmartFake implements _i12.WebOptions {
  _FakeWebOptions_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMacOsOptions_16 extends _i1.SmartFake implements _i12.MacOsOptions {
  _FakeMacOsOptions_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthConfig_17 extends _i1.SmartFake implements _i13.AuthConfig {
  _FakeAuthConfig_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIosUtsname_18 extends _i1.SmartFake implements _i14.IosUtsname {
  _FakeIosUtsname_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAndroidBuildVersion_19 extends _i1.SmartFake
    implements _i15.AndroidBuildVersion {
  _FakeAndroidBuildVersion_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAndroidDeviceInfo_20 extends _i1.SmartFake
    implements _i15.AndroidDeviceInfo {
  _FakeAndroidDeviceInfo_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIosDeviceInfo_21 extends _i1.SmartFake
    implements _i14.IosDeviceInfo {
  _FakeIosDeviceInfo_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLinuxDeviceInfo_22 extends _i1.SmartFake
    implements _i16.LinuxDeviceInfo {
  _FakeLinuxDeviceInfo_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebBrowserInfo_23 extends _i1.SmartFake
    implements _i17.WebBrowserInfo {
  _FakeWebBrowserInfo_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMacOsDeviceInfo_24 extends _i1.SmartFake
    implements _i18.MacOsDeviceInfo {
  _FakeMacOsDeviceInfo_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWindowsDeviceInfo_25 extends _i1.SmartFake
    implements _i19.WindowsDeviceInfo {
  _FakeWindowsDeviceInfo_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseDeviceInfo_26 extends _i1.SmartFake
    implements _i20.BaseDeviceInfo {
  _FakeBaseDeviceInfo_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAPIEndpoint_27 extends _i1.SmartFake implements _i21.APIEndpoint {
  _FakeAPIEndpoint_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginUser_28 extends _i1.SmartFake implements _i22.LoginUser {
  _FakeLoginUser_28(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthRepository_29 extends _i1.SmartFake
    implements _i23.AuthRepository {
  _FakeAuthRepository_29(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i7.Dio {
  MockDio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeBaseOptions_0(this, Invocation.getter(#options)),
          )
          as _i2.BaseOptions);

  @override
  _i3.Interceptors get interceptors =>
      (super.noSuchMethod(
            Invocation.getter(#interceptors),
            returnValue: _FakeInterceptors_1(
              this,
              Invocation.getter(#interceptors),
            ),
          )
          as _i3.Interceptors);

  @override
  _i4.HttpClientAdapter get httpClientAdapter =>
      (super.noSuchMethod(
            Invocation.getter(#httpClientAdapter),
            returnValue: _FakeHttpClientAdapter_2(
              this,
              Invocation.getter(#httpClientAdapter),
            ),
          )
          as _i4.HttpClientAdapter);

  @override
  _i5.Transformer get transformer =>
      (super.noSuchMethod(
            Invocation.getter(#transformer),
            returnValue: _FakeTransformer_3(
              this,
              Invocation.getter(#transformer),
            ),
          )
          as _i5.Transformer);

  @override
  set options(_i2.BaseOptions? value) => super.noSuchMethod(
    Invocation.setter(#options, value),
    returnValueForMissingStub: null,
  );

  @override
  set httpClientAdapter(_i4.HttpClientAdapter? value) => super.noSuchMethod(
    Invocation.setter(#httpClientAdapter, value),
    returnValueForMissingStub: null,
  );

  @override
  set transformer(_i5.Transformer? value) => super.noSuchMethod(
    Invocation.setter(#transformer, value),
    returnValueForMissingStub: null,
  );

  @override
  void close({bool? force = false}) => super.noSuchMethod(
    Invocation.method(#close, [], {#force: force}),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<_i6.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i24.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #head,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i11.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #head,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i6.Response<T>>);

  @override
  _i11.Future<_i6.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i24.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #headUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i11.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #headUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i11.Future<_i6.Response<T>>);

  @override
  _i11.Future<_i6.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i24.CancelToken? cancelToken,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i6.Response<T>>);

  @override
  _i11.Future<_i6.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i24.CancelToken? cancelToken,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #getUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i6.Response<T>>);

  @override
  _i11.Future<_i6.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i24.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i6.Response<T>>);

  @override
  _i11.Future<_i6.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i24.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #postUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i6.Response<T>>);

  @override
  _i11.Future<_i6.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i24.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i6.Response<T>>);

  @override
  _i11.Future<_i6.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i24.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #putUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i6.Response<T>>);

  @override
  _i11.Future<_i6.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i24.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #patch,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i6.Response<T>>);

  @override
  _i11.Future<_i6.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i24.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patchUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #patchUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i6.Response<T>>);

  @override
  _i11.Future<_i6.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i24.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i11.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i6.Response<T>>);

  @override
  _i11.Future<_i6.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i24.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i11.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #deleteUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i11.Future<_i6.Response<T>>);

  @override
  _i11.Future<_i6.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i2.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i24.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i2.FileAccessMode? fileAccessMode = _i2.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #download,
              [urlPath, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i11.Future<_i6.Response<dynamic>>.value(
              _FakeResponse_4<dynamic>(
                this,
                Invocation.method(
                  #download,
                  [urlPath, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i6.Response<dynamic>>);

  @override
  _i11.Future<_i6.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i2.ProgressCallback? onReceiveProgress,
    _i24.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i2.FileAccessMode? fileAccessMode = _i2.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadUri,
              [uri, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i11.Future<_i6.Response<dynamic>>.value(
              _FakeResponse_4<dynamic>(
                this,
                Invocation.method(
                  #downloadUri,
                  [uri, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i6.Response<dynamic>>);

  @override
  _i11.Future<_i6.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i24.CancelToken? cancelToken,
    _i2.Options? options,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #request,
              [url],
              {
                #data: data,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #request,
                  [url],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i6.Response<T>>);

  @override
  _i11.Future<_i6.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i24.CancelToken? cancelToken,
    _i2.Options? options,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestUri,
              [uri],
              {
                #data: data,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #requestUri,
                  [uri],
                  {
                    #data: data,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i6.Response<T>>);

  @override
  _i11.Future<_i6.Response<T>> fetch<T>(_i2.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
            Invocation.method(#fetch, [requestOptions]),
            returnValue: _i11.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(#fetch, [requestOptions]),
              ),
            ),
          )
          as _i11.Future<_i6.Response<T>>);

  @override
  _i7.Dio clone({
    _i2.BaseOptions? options,
    _i3.Interceptors? interceptors,
    _i4.HttpClientAdapter? httpClientAdapter,
    _i5.Transformer? transformer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#clone, [], {
              #options: options,
              #interceptors: interceptors,
              #httpClientAdapter: httpClientAdapter,
              #transformer: transformer,
            }),
            returnValue: _FakeDio_5(
              this,
              Invocation.method(#clone, [], {
                #options: options,
                #interceptors: interceptors,
                #httpClientAdapter: httpClientAdapter,
                #transformer: transformer,
              }),
            ),
          )
          as _i7.Dio);
}

/// A class which mocks [APIConfig].
///
/// See the documentation for Mockito's code generation for more information.
class MockAPIConfig extends _i1.Mock implements _i9.APIConfig {
  MockAPIConfig() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get apiKey =>
      (super.noSuchMethod(
            Invocation.getter(#apiKey),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#apiKey),
            ),
          )
          as String);

  @override
  _i26.Environment get environment =>
      (super.noSuchMethod(
            Invocation.getter(#environment),
            returnValue: _i26.Environment.dev,
          )
          as _i26.Environment);

  @override
  _i8.BaseUrlConfig get baseUrlConfig =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrlConfig),
            returnValue: _FakeBaseUrlConfig_6(
              this,
              Invocation.getter(#baseUrlConfig),
            ),
          )
          as _i8.BaseUrlConfig);

  @override
  String get appName =>
      (super.noSuchMethod(
            Invocation.getter(#appName),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#appName),
            ),
          )
          as String);

  @override
  String get defaultBaseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#defaultBaseUrl),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#defaultBaseUrl),
            ),
          )
          as String);

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  bool get isDev =>
      (super.noSuchMethod(Invocation.getter(#isDev), returnValue: false)
          as bool);

  @override
  bool get isStage =>
      (super.noSuchMethod(Invocation.getter(#isStage), returnValue: false)
          as bool);

  @override
  bool get isProd =>
      (super.noSuchMethod(Invocation.getter(#isProd), returnValue: false)
          as bool);

  @override
  List<Object?> get props =>
      (super.noSuchMethod(Invocation.getter(#props), returnValue: <Object?>[])
          as List<Object?>);

  @override
  _i9.APIConfig copyWith({
    String? baseUrl,
    String? apiKey,
    _i26.Environment? environment,
    _i8.BaseUrlConfig? baseUrlConfig,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #baseUrl: baseUrl,
              #apiKey: apiKey,
              #environment: environment,
              #baseUrlConfig: baseUrlConfig,
            }),
            returnValue: _FakeAPIConfig_7(
              this,
              Invocation.method(#copyWith, [], {
                #baseUrl: baseUrl,
                #apiKey: apiKey,
                #environment: environment,
                #baseUrlConfig: baseUrlConfig,
              }),
            ),
          )
          as _i9.APIConfig);

  @override
  String baseUrlFor(_i27.BaseUrlType? type) =>
      (super.noSuchMethod(
            Invocation.method(#baseUrlFor, [type]),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.method(#baseUrlFor, [type]),
            ),
          )
          as String);
}

/// A class which mocks [APIEndpoint].
///
/// See the documentation for Mockito's code generation for more information.
class MockAPIEndpoint extends _i1.Mock implements _i21.APIEndpoint {
  MockAPIEndpoint() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i21.HttpMethod get method =>
      (super.noSuchMethod(
            Invocation.getter(#method),
            returnValue: _i21.HttpMethod.get,
          )
          as _i21.HttpMethod);

  @override
  bool get isFullUrl =>
      (super.noSuchMethod(Invocation.getter(#isFullUrl), returnValue: false)
          as bool);

  @override
  bool get isCompositeUrl =>
      (super.noSuchMethod(
            Invocation.getter(#isCompositeUrl),
            returnValue: false,
          )
          as bool);

  @override
  String get path =>
      (super.noSuchMethod(
            Invocation.getter(#path),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#path),
            ),
          )
          as String);
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i28.Connectivity {
  MockConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Stream<List<_i29.ConnectivityResult>> get onConnectivityChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onConnectivityChanged),
            returnValue: _i11.Stream<List<_i29.ConnectivityResult>>.empty(),
          )
          as _i11.Stream<List<_i29.ConnectivityResult>>);

  @override
  _i11.Future<List<_i29.ConnectivityResult>> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i11.Future<List<_i29.ConnectivityResult>>.value(
              <_i29.ConnectivityResult>[],
            ),
          )
          as _i11.Future<List<_i29.ConnectivityResult>>);
}

/// A class which mocks [RequestInterceptorHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequestInterceptorHandler extends _i1.Mock
    implements _i3.RequestInterceptorHandler {
  MockRequestInterceptorHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i3.InterceptorState<dynamic>> get future =>
      (super.noSuchMethod(
            Invocation.getter(#future),
            returnValue: _i11.Future<_i3.InterceptorState<dynamic>>.value(
              _FakeInterceptorState_8<dynamic>(
                this,
                Invocation.getter(#future),
              ),
            ),
          )
          as _i11.Future<_i3.InterceptorState<dynamic>>);

  @override
  bool get isCompleted =>
      (super.noSuchMethod(Invocation.getter(#isCompleted), returnValue: false)
          as bool);

  @override
  void next(_i2.RequestOptions? requestOptions) => super.noSuchMethod(
    Invocation.method(#next, [requestOptions]),
    returnValueForMissingStub: null,
  );

  @override
  void resolve(
    _i6.Response<dynamic>? response, [
    bool? callFollowingResponseInterceptor = false,
  ]) => super.noSuchMethod(
    Invocation.method(#resolve, [response, callFollowingResponseInterceptor]),
    returnValueForMissingStub: null,
  );

  @override
  void reject(
    _i30.DioException? error, [
    bool? callFollowingErrorInterceptor = false,
  ]) => super.noSuchMethod(
    Invocation.method(#reject, [error, callFollowingErrorInterceptor]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [UserModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserModel extends _i1.Mock implements _i31.UserModel {
  MockUserModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i25.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  String get email =>
      (super.noSuchMethod(
            Invocation.getter(#email),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#email),
            ),
          )
          as String);

  @override
  bool get isVerified =>
      (super.noSuchMethod(Invocation.getter(#isVerified), returnValue: false)
          as bool);

  @override
  List<Object?> get props =>
      (super.noSuchMethod(Invocation.getter(#props), returnValue: <Object?>[])
          as List<Object?>);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i10.User toEntity() =>
      (super.noSuchMethod(
            Invocation.method(#toEntity, []),
            returnValue: _FakeUser_9(this, Invocation.method(#toEntity, [])),
          )
          as _i10.User);

  @override
  _i10.User copyWith({
    String? id,
    String? email,
    String? name,
    String? avatarUrl,
    bool? isVerified,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #id: id,
              #email: email,
              #name: name,
              #avatarUrl: avatarUrl,
              #isVerified: isVerified,
            }),
            returnValue: _FakeUser_9(
              this,
              Invocation.method(#copyWith, [], {
                #id: id,
                #email: email,
                #name: name,
                #avatarUrl: avatarUrl,
                #isVerified: isVerified,
              }),
            ),
          )
          as _i10.User);
}

/// A class which mocks [APIClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAPIClient extends _i1.Mock implements _i32.APIClient {
  MockAPIClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<Model> get<Model>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? queryParameters,
    required _i32.APICallback<dynamic>? fromJson,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {
                #data: data,
                #headers: headers,
                #queryParameters: queryParameters,
                #fromJson: fromJson,
              },
            ),
            returnValue:
                _i25.ifNotNull(
                  _i25.dummyValueOrNull<Model>(
                    this,
                    Invocation.method(
                      #get,
                      [path],
                      {
                        #data: data,
                        #headers: headers,
                        #queryParameters: queryParameters,
                        #fromJson: fromJson,
                      },
                    ),
                  ),
                  (Model v) => _i11.Future<Model>.value(v),
                ) ??
                _FakeFuture_10<Model>(
                  this,
                  Invocation.method(
                    #get,
                    [path],
                    {
                      #data: data,
                      #headers: headers,
                      #queryParameters: queryParameters,
                      #fromJson: fromJson,
                    },
                  ),
                ),
          )
          as _i11.Future<Model>);

  @override
  _i11.Future<Model> post<Model>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? queryParameters,
    required _i32.APICallback<dynamic>? fromJson,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #data: data,
                #headers: headers,
                #queryParameters: queryParameters,
                #fromJson: fromJson,
              },
            ),
            returnValue:
                _i25.ifNotNull(
                  _i25.dummyValueOrNull<Model>(
                    this,
                    Invocation.method(
                      #post,
                      [path],
                      {
                        #data: data,
                        #headers: headers,
                        #queryParameters: queryParameters,
                        #fromJson: fromJson,
                      },
                    ),
                  ),
                  (Model v) => _i11.Future<Model>.value(v),
                ) ??
                _FakeFuture_10<Model>(
                  this,
                  Invocation.method(
                    #post,
                    [path],
                    {
                      #data: data,
                      #headers: headers,
                      #queryParameters: queryParameters,
                      #fromJson: fromJson,
                    },
                  ),
                ),
          )
          as _i11.Future<Model>);

  @override
  _i11.Future<Model> put<Model>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? queryParameters,
    required _i32.APICallback<dynamic>? fromJson,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #data: data,
                #headers: headers,
                #queryParameters: queryParameters,
                #fromJson: fromJson,
              },
            ),
            returnValue:
                _i25.ifNotNull(
                  _i25.dummyValueOrNull<Model>(
                    this,
                    Invocation.method(
                      #put,
                      [path],
                      {
                        #data: data,
                        #headers: headers,
                        #queryParameters: queryParameters,
                        #fromJson: fromJson,
                      },
                    ),
                  ),
                  (Model v) => _i11.Future<Model>.value(v),
                ) ??
                _FakeFuture_10<Model>(
                  this,
                  Invocation.method(
                    #put,
                    [path],
                    {
                      #data: data,
                      #headers: headers,
                      #queryParameters: queryParameters,
                      #fromJson: fromJson,
                    },
                  ),
                ),
          )
          as _i11.Future<Model>);

  @override
  _i11.Future<Model> delete<Model>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? queryParameters,
    required _i32.APICallback<dynamic>? fromJson,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #data: data,
                #headers: headers,
                #queryParameters: queryParameters,
                #fromJson: fromJson,
              },
            ),
            returnValue:
                _i25.ifNotNull(
                  _i25.dummyValueOrNull<Model>(
                    this,
                    Invocation.method(
                      #delete,
                      [path],
                      {
                        #data: data,
                        #headers: headers,
                        #queryParameters: queryParameters,
                        #fromJson: fromJson,
                      },
                    ),
                  ),
                  (Model v) => _i11.Future<Model>.value(v),
                ) ??
                _FakeFuture_10<Model>(
                  this,
                  Invocation.method(
                    #delete,
                    [path],
                    {
                      #data: data,
                      #headers: headers,
                      #queryParameters: queryParameters,
                      #fromJson: fromJson,
                    },
                  ),
                ),
          )
          as _i11.Future<Model>);

  @override
  _i11.Future<Model> patch<Model>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? queryParameters,
    required _i32.APICallback<dynamic>? fromJson,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [path],
              {
                #data: data,
                #headers: headers,
                #queryParameters: queryParameters,
                #fromJson: fromJson,
              },
            ),
            returnValue:
                _i25.ifNotNull(
                  _i25.dummyValueOrNull<Model>(
                    this,
                    Invocation.method(
                      #patch,
                      [path],
                      {
                        #data: data,
                        #headers: headers,
                        #queryParameters: queryParameters,
                        #fromJson: fromJson,
                      },
                    ),
                  ),
                  (Model v) => _i11.Future<Model>.value(v),
                ) ??
                _FakeFuture_10<Model>(
                  this,
                  Invocation.method(
                    #patch,
                    [path],
                    {
                      #data: data,
                      #headers: headers,
                      #queryParameters: queryParameters,
                      #fromJson: fromJson,
                    },
                  ),
                ),
          )
          as _i11.Future<Model>);

  @override
  _i11.Future<Model> request<Model>(
    _i2.RequestOptions? options, {
    required _i32.APICallback<dynamic>? fromJson,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#request, [options], {#fromJson: fromJson}),
            returnValue:
                _i25.ifNotNull(
                  _i25.dummyValueOrNull<Model>(
                    this,
                    Invocation.method(
                      #request,
                      [options],
                      {#fromJson: fromJson},
                    ),
                  ),
                  (Model v) => _i11.Future<Model>.value(v),
                ) ??
                _FakeFuture_10<Model>(
                  this,
                  Invocation.method(#request, [options], {#fromJson: fromJson}),
                ),
          )
          as _i11.Future<Model>);

  @override
  _i11.Future<Model> fetch<Model>({
    bool? isFormData = false,
    required _i21.APIEndpoint? target,
    required _i32.APICallback<dynamic>? fromJson,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetch, [], {
              #isFormData: isFormData,
              #target: target,
              #fromJson: fromJson,
            }),
            returnValue:
                _i25.ifNotNull(
                  _i25.dummyValueOrNull<Model>(
                    this,
                    Invocation.method(#fetch, [], {
                      #isFormData: isFormData,
                      #target: target,
                      #fromJson: fromJson,
                    }),
                  ),
                  (Model v) => _i11.Future<Model>.value(v),
                ) ??
                _FakeFuture_10<Model>(
                  this,
                  Invocation.method(#fetch, [], {
                    #isFormData: isFormData,
                    #target: target,
                    #fromJson: fromJson,
                  }),
                ),
          )
          as _i11.Future<Model>);
}

/// A class which mocks [NetworkConnectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkConnectivity extends _i1.Mock
    implements _i33.NetworkConnectivity {
  MockNetworkConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i12.FlutterSecureStorage {
  MockFlutterSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.IOSOptions get iOptions =>
      (super.noSuchMethod(
            Invocation.getter(#iOptions),
            returnValue: _FakeIOSOptions_11(this, Invocation.getter(#iOptions)),
          )
          as _i12.IOSOptions);

  @override
  _i12.AndroidOptions get aOptions =>
      (super.noSuchMethod(
            Invocation.getter(#aOptions),
            returnValue: _FakeAndroidOptions_12(
              this,
              Invocation.getter(#aOptions),
            ),
          )
          as _i12.AndroidOptions);

  @override
  _i12.LinuxOptions get lOptions =>
      (super.noSuchMethod(
            Invocation.getter(#lOptions),
            returnValue: _FakeLinuxOptions_13(
              this,
              Invocation.getter(#lOptions),
            ),
          )
          as _i12.LinuxOptions);

  @override
  _i12.WindowsOptions get wOptions =>
      (super.noSuchMethod(
            Invocation.getter(#wOptions),
            returnValue: _FakeWindowsOptions_14(
              this,
              Invocation.getter(#wOptions),
            ),
          )
          as _i12.WindowsOptions);

  @override
  _i12.WebOptions get webOptions =>
      (super.noSuchMethod(
            Invocation.getter(#webOptions),
            returnValue: _FakeWebOptions_15(
              this,
              Invocation.getter(#webOptions),
            ),
          )
          as _i12.WebOptions);

  @override
  _i12.MacOsOptions get mOptions =>
      (super.noSuchMethod(
            Invocation.getter(#mOptions),
            returnValue: _FakeMacOsOptions_16(
              this,
              Invocation.getter(#mOptions),
            ),
          )
          as _i12.MacOsOptions);

  @override
  void registerListener({
    required String? key,
    required _i34.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#registerListener, [], {#key: key, #listener: listener}),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterListener({
    required String? key,
    required _i34.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#unregisterListener, [], {
      #key: key,
      #listener: listener,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterAllListenersForKey({required String? key}) =>
      super.noSuchMethod(
        Invocation.method(#unregisterAllListenersForKey, [], {#key: key}),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListeners() => super.noSuchMethod(
    Invocation.method(#unregisterAllListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<void> write({
    required String? key,
    required String? value,
    _i12.IOSOptions? iOptions,
    _i12.AndroidOptions? aOptions,
    _i12.LinuxOptions? lOptions,
    _i12.WebOptions? webOptions,
    _i12.MacOsOptions? mOptions,
    _i12.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {
              #key: key,
              #value: value,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<String?> read({
    required String? key,
    _i12.IOSOptions? iOptions,
    _i12.AndroidOptions? aOptions,
    _i12.LinuxOptions? lOptions,
    _i12.WebOptions? webOptions,
    _i12.MacOsOptions? mOptions,
    _i12.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i11.Future<String?>.value(),
          )
          as _i11.Future<String?>);

  @override
  _i11.Future<bool> containsKey({
    required String? key,
    _i12.IOSOptions? iOptions,
    _i12.AndroidOptions? aOptions,
    _i12.LinuxOptions? lOptions,
    _i12.WebOptions? webOptions,
    _i12.MacOsOptions? mOptions,
    _i12.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<void> delete({
    required String? key,
    _i12.IOSOptions? iOptions,
    _i12.AndroidOptions? aOptions,
    _i12.LinuxOptions? lOptions,
    _i12.WebOptions? webOptions,
    _i12.MacOsOptions? mOptions,
    _i12.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<Map<String, String>> readAll({
    _i12.IOSOptions? iOptions,
    _i12.AndroidOptions? aOptions,
    _i12.LinuxOptions? lOptions,
    _i12.WebOptions? webOptions,
    _i12.MacOsOptions? mOptions,
    _i12.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i11.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i11.Future<Map<String, String>>);

  @override
  _i11.Future<void> deleteAll({
    _i12.IOSOptions? iOptions,
    _i12.AndroidOptions? aOptions,
    _i12.LinuxOptions? lOptions,
    _i12.WebOptions? webOptions,
    _i12.MacOsOptions? mOptions,
    _i12.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<bool?> isCupertinoProtectedDataAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isCupertinoProtectedDataAvailable, []),
            returnValue: _i11.Future<bool?>.value(),
          )
          as _i11.Future<bool?>);
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i35.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> delete(dynamic key) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [key]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  bool has(dynamic key) =>
      (super.noSuchMethod(Invocation.method(#has, [key]), returnValue: false)
          as bool);

  @override
  _i11.Future<void> put({required dynamic key, required dynamic value}) =>
      (super.noSuchMethod(
            Invocation.method(#put, [], {#key: key, #value: value}),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> putJson({required dynamic key, required dynamic value}) =>
      (super.noSuchMethod(
            Invocation.method(#putJson, [], {#key: key, #value: value}),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  T? getJson<T>({
    required dynamic key,
    required _i35.StorageCallback<T>? fromJson,
    dynamic defaultValue,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getJson, [], {
              #key: key,
              #fromJson: fromJson,
              #defaultValue: defaultValue,
            }),
          )
          as T?);

  @override
  List<T> getList<T>({
    required dynamic key,
    required _i35.StorageCallback<T>? fromJson,
    dynamic defaultValue,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getList, [], {
              #key: key,
              #fromJson: fromJson,
              #defaultValue: defaultValue,
            }),
            returnValue: <T>[],
          )
          as List<T>);
}

/// A class which mocks [SecureStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageService extends _i1.Mock
    implements _i36.SecureStorageService {
  MockSecureStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i11.Future<String?>.value(),
          )
          as _i11.Future<String?>);

  @override
  _i11.Future<void> deleteToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteToken, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> write({required String? key, required String? value}) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {#key: key, #value: value}),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<String?> read({required String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {#key: key}),
            returnValue: _i11.Future<String?>.value(),
          )
          as _i11.Future<String?>);

  @override
  _i11.Future<void> delete({required String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {#key: key}),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [EnvironmentConfigService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEnvironmentConfigService extends _i1.Mock
    implements _i37.EnvironmentConfigService {
  MockEnvironmentConfigService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.APIConfig get currentApiConfig =>
      (super.noSuchMethod(
            Invocation.getter(#currentApiConfig),
            returnValue: _FakeAPIConfig_7(
              this,
              Invocation.getter(#currentApiConfig),
            ),
          )
          as _i9.APIConfig);

  @override
  _i26.Environment get currentEnvironment =>
      (super.noSuchMethod(
            Invocation.getter(#currentEnvironment),
            returnValue: _i26.Environment.dev,
          )
          as _i26.Environment);

  @override
  _i13.AuthConfig getAuthConfigForEnvironment(_i26.Environment? env) =>
      (super.noSuchMethod(
            Invocation.method(#getAuthConfigForEnvironment, [env]),
            returnValue: _FakeAuthConfig_17(
              this,
              Invocation.method(#getAuthConfigForEnvironment, [env]),
            ),
          )
          as _i13.AuthConfig);

  @override
  _i9.APIConfig getConfigForEnvironment(_i26.Environment? env) =>
      (super.noSuchMethod(
            Invocation.method(#getConfigForEnvironment, [env]),
            returnValue: _FakeAPIConfig_7(
              this,
              Invocation.method(#getConfigForEnvironment, [env]),
            ),
          )
          as _i9.APIConfig);

  @override
  _i11.Future<void> updateConfiguration(
    _i26.Environment? environment, {
    _i38.BaseUrlConfigModel? baseUrlConfig,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateConfiguration,
              [environment],
              {#baseUrlConfig: baseUrlConfig},
            ),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [IosUtsname].
///
/// See the documentation for Mockito's code generation for more information.
class MockIosUtsname extends _i1.Mock implements _i14.IosUtsname {
  MockIosUtsname() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get sysname =>
      (super.noSuchMethod(
            Invocation.getter(#sysname),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#sysname),
            ),
          )
          as String);

  @override
  String get nodename =>
      (super.noSuchMethod(
            Invocation.getter(#nodename),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#nodename),
            ),
          )
          as String);

  @override
  String get release =>
      (super.noSuchMethod(
            Invocation.getter(#release),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#release),
            ),
          )
          as String);

  @override
  String get version =>
      (super.noSuchMethod(
            Invocation.getter(#version),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#version),
            ),
          )
          as String);

  @override
  String get machine =>
      (super.noSuchMethod(
            Invocation.getter(#machine),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#machine),
            ),
          )
          as String);
}

/// A class which mocks [IosDeviceInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockIosDeviceInfo extends _i1.Mock implements _i14.IosDeviceInfo {
  MockIosDeviceInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  String get systemName =>
      (super.noSuchMethod(
            Invocation.getter(#systemName),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#systemName),
            ),
          )
          as String);

  @override
  String get systemVersion =>
      (super.noSuchMethod(
            Invocation.getter(#systemVersion),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#systemVersion),
            ),
          )
          as String);

  @override
  String get model =>
      (super.noSuchMethod(
            Invocation.getter(#model),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#model),
            ),
          )
          as String);

  @override
  String get modelName =>
      (super.noSuchMethod(
            Invocation.getter(#modelName),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#modelName),
            ),
          )
          as String);

  @override
  String get localizedModel =>
      (super.noSuchMethod(
            Invocation.getter(#localizedModel),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#localizedModel),
            ),
          )
          as String);

  @override
  bool get isPhysicalDevice =>
      (super.noSuchMethod(
            Invocation.getter(#isPhysicalDevice),
            returnValue: false,
          )
          as bool);

  @override
  int get physicalRamSize =>
      (super.noSuchMethod(Invocation.getter(#physicalRamSize), returnValue: 0)
          as int);

  @override
  int get availableRamSize =>
      (super.noSuchMethod(Invocation.getter(#availableRamSize), returnValue: 0)
          as int);

  @override
  bool get isiOSAppOnMac =>
      (super.noSuchMethod(Invocation.getter(#isiOSAppOnMac), returnValue: false)
          as bool);

  @override
  _i14.IosUtsname get utsname =>
      (super.noSuchMethod(
            Invocation.getter(#utsname),
            returnValue: _FakeIosUtsname_18(this, Invocation.getter(#utsname)),
          )
          as _i14.IosUtsname);

  @override
  int get freeDiskSize =>
      (super.noSuchMethod(Invocation.getter(#freeDiskSize), returnValue: 0)
          as int);

  @override
  int get totalDiskSize =>
      (super.noSuchMethod(Invocation.getter(#totalDiskSize), returnValue: 0)
          as int);

  @override
  Map<String, dynamic> get data =>
      (super.noSuchMethod(
            Invocation.getter(#data),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  Map<String, dynamic> toMap() =>
      (super.noSuchMethod(
            Invocation.method(#toMap, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [AndroidDeviceInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAndroidDeviceInfo extends _i1.Mock implements _i15.AndroidDeviceInfo {
  MockAndroidDeviceInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.AndroidBuildVersion get version =>
      (super.noSuchMethod(
            Invocation.getter(#version),
            returnValue: _FakeAndroidBuildVersion_19(
              this,
              Invocation.getter(#version),
            ),
          )
          as _i15.AndroidBuildVersion);

  @override
  String get board =>
      (super.noSuchMethod(
            Invocation.getter(#board),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#board),
            ),
          )
          as String);

  @override
  String get bootloader =>
      (super.noSuchMethod(
            Invocation.getter(#bootloader),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#bootloader),
            ),
          )
          as String);

  @override
  String get brand =>
      (super.noSuchMethod(
            Invocation.getter(#brand),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#brand),
            ),
          )
          as String);

  @override
  String get device =>
      (super.noSuchMethod(
            Invocation.getter(#device),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#device),
            ),
          )
          as String);

  @override
  String get display =>
      (super.noSuchMethod(
            Invocation.getter(#display),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#display),
            ),
          )
          as String);

  @override
  String get fingerprint =>
      (super.noSuchMethod(
            Invocation.getter(#fingerprint),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#fingerprint),
            ),
          )
          as String);

  @override
  String get hardware =>
      (super.noSuchMethod(
            Invocation.getter(#hardware),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#hardware),
            ),
          )
          as String);

  @override
  String get host =>
      (super.noSuchMethod(
            Invocation.getter(#host),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#host),
            ),
          )
          as String);

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i25.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  String get manufacturer =>
      (super.noSuchMethod(
            Invocation.getter(#manufacturer),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#manufacturer),
            ),
          )
          as String);

  @override
  String get model =>
      (super.noSuchMethod(
            Invocation.getter(#model),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#model),
            ),
          )
          as String);

  @override
  String get product =>
      (super.noSuchMethod(
            Invocation.getter(#product),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#product),
            ),
          )
          as String);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  List<String> get supported32BitAbis =>
      (super.noSuchMethod(
            Invocation.getter(#supported32BitAbis),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<String> get supported64BitAbis =>
      (super.noSuchMethod(
            Invocation.getter(#supported64BitAbis),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<String> get supportedAbis =>
      (super.noSuchMethod(
            Invocation.getter(#supportedAbis),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  String get tags =>
      (super.noSuchMethod(
            Invocation.getter(#tags),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#tags),
            ),
          )
          as String);

  @override
  String get type =>
      (super.noSuchMethod(
            Invocation.getter(#type),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#type),
            ),
          )
          as String);

  @override
  bool get isPhysicalDevice =>
      (super.noSuchMethod(
            Invocation.getter(#isPhysicalDevice),
            returnValue: false,
          )
          as bool);

  @override
  int get freeDiskSize =>
      (super.noSuchMethod(Invocation.getter(#freeDiskSize), returnValue: 0)
          as int);

  @override
  int get totalDiskSize =>
      (super.noSuchMethod(Invocation.getter(#totalDiskSize), returnValue: 0)
          as int);

  @override
  List<String> get systemFeatures =>
      (super.noSuchMethod(
            Invocation.getter(#systemFeatures),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  bool get isLowRamDevice =>
      (super.noSuchMethod(
            Invocation.getter(#isLowRamDevice),
            returnValue: false,
          )
          as bool);

  @override
  int get physicalRamSize =>
      (super.noSuchMethod(Invocation.getter(#physicalRamSize), returnValue: 0)
          as int);

  @override
  int get availableRamSize =>
      (super.noSuchMethod(Invocation.getter(#availableRamSize), returnValue: 0)
          as int);

  @override
  Map<String, dynamic> get data =>
      (super.noSuchMethod(
            Invocation.getter(#data),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  Map<String, dynamic> toMap() =>
      (super.noSuchMethod(
            Invocation.method(#toMap, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [DeviceInfoPlugin].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceInfoPlugin extends _i1.Mock implements _i39.DeviceInfoPlugin {
  MockDeviceInfoPlugin() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i15.AndroidDeviceInfo> get androidInfo =>
      (super.noSuchMethod(
            Invocation.getter(#androidInfo),
            returnValue: _i11.Future<_i15.AndroidDeviceInfo>.value(
              _FakeAndroidDeviceInfo_20(this, Invocation.getter(#androidInfo)),
            ),
          )
          as _i11.Future<_i15.AndroidDeviceInfo>);

  @override
  _i11.Future<_i14.IosDeviceInfo> get iosInfo =>
      (super.noSuchMethod(
            Invocation.getter(#iosInfo),
            returnValue: _i11.Future<_i14.IosDeviceInfo>.value(
              _FakeIosDeviceInfo_21(this, Invocation.getter(#iosInfo)),
            ),
          )
          as _i11.Future<_i14.IosDeviceInfo>);

  @override
  _i11.Future<_i16.LinuxDeviceInfo> get linuxInfo =>
      (super.noSuchMethod(
            Invocation.getter(#linuxInfo),
            returnValue: _i11.Future<_i16.LinuxDeviceInfo>.value(
              _FakeLinuxDeviceInfo_22(this, Invocation.getter(#linuxInfo)),
            ),
          )
          as _i11.Future<_i16.LinuxDeviceInfo>);

  @override
  _i11.Future<_i17.WebBrowserInfo> get webBrowserInfo =>
      (super.noSuchMethod(
            Invocation.getter(#webBrowserInfo),
            returnValue: _i11.Future<_i17.WebBrowserInfo>.value(
              _FakeWebBrowserInfo_23(this, Invocation.getter(#webBrowserInfo)),
            ),
          )
          as _i11.Future<_i17.WebBrowserInfo>);

  @override
  _i11.Future<_i18.MacOsDeviceInfo> get macOsInfo =>
      (super.noSuchMethod(
            Invocation.getter(#macOsInfo),
            returnValue: _i11.Future<_i18.MacOsDeviceInfo>.value(
              _FakeMacOsDeviceInfo_24(this, Invocation.getter(#macOsInfo)),
            ),
          )
          as _i11.Future<_i18.MacOsDeviceInfo>);

  @override
  _i11.Future<_i19.WindowsDeviceInfo> get windowsInfo =>
      (super.noSuchMethod(
            Invocation.getter(#windowsInfo),
            returnValue: _i11.Future<_i19.WindowsDeviceInfo>.value(
              _FakeWindowsDeviceInfo_25(this, Invocation.getter(#windowsInfo)),
            ),
          )
          as _i11.Future<_i19.WindowsDeviceInfo>);

  @override
  _i11.Future<_i20.BaseDeviceInfo> get deviceInfo =>
      (super.noSuchMethod(
            Invocation.getter(#deviceInfo),
            returnValue: _i11.Future<_i20.BaseDeviceInfo>.value(
              _FakeBaseDeviceInfo_26(this, Invocation.getter(#deviceInfo)),
            ),
          )
          as _i11.Future<_i20.BaseDeviceInfo>);
}

/// A class which mocks [PlatformChecker].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlatformChecker extends _i1.Mock implements _i40.PlatformChecker {
  MockPlatformChecker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isIOS =>
      (super.noSuchMethod(Invocation.getter(#isIOS), returnValue: false)
          as bool);

  @override
  bool get isAndroid =>
      (super.noSuchMethod(Invocation.getter(#isAndroid), returnValue: false)
          as bool);

  @override
  bool get isMobile =>
      (super.noSuchMethod(Invocation.getter(#isMobile), returnValue: false)
          as bool);
}

/// A class which mocks [DeviceServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceServices extends _i1.Mock implements _i41.DeviceServices {
  MockDeviceServices() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<String?> getDeviceModel() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceModel, []),
            returnValue: _i11.Future<String?>.value(),
          )
          as _i11.Future<String?>);
}

/// A class which mocks [AuthEndpoints].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthEndpoints extends _i1.Mock implements _i42.AuthEndpoints {
  MockAuthEndpoints() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i21.APIEndpoint login(_i43.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _FakeAPIEndpoint_27(
              this,
              Invocation.method(#login, [request]),
            ),
          )
          as _i21.APIEndpoint);

  @override
  _i21.APIEndpoint register(_i44.RegisterRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _FakeAPIEndpoint_27(
              this,
              Invocation.method(#register, [request]),
            ),
          )
          as _i21.APIEndpoint);

  @override
  _i21.APIEndpoint logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _FakeAPIEndpoint_27(
              this,
              Invocation.method(#logout, []),
            ),
          )
          as _i21.APIEndpoint);

  @override
  _i21.APIEndpoint deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _FakeAPIEndpoint_27(
              this,
              Invocation.method(#deleteAccount, []),
            ),
          )
          as _i21.APIEndpoint);
}

/// A class which mocks [AuthLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSource extends _i1.Mock
    implements _i45.AuthLocalDataSource {
  MockAuthLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i11.Future<String?>.value(),
          )
          as _i11.Future<String?>);

  @override
  _i11.Future<void> saveUser(_i31.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveUser, [user]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> deleteUser() =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  bool hasUser() =>
      (super.noSuchMethod(Invocation.method(#hasUser, []), returnValue: false)
          as bool);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i46.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i22.LoginUser> login(_i43.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i11.Future<_i22.LoginUser>.value(
              _FakeLoginUser_28(this, Invocation.method(#login, [request])),
            ),
          )
          as _i11.Future<_i22.LoginUser>);

  @override
  _i11.Future<_i22.LoginUser> register(_i44.RegisterRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i11.Future<_i22.LoginUser>.value(
              _FakeLoginUser_28(this, Invocation.method(#register, [request])),
            ),
          )
          as _i11.Future<_i22.LoginUser>);

  @override
  _i11.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i23.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i10.User> login(_i47.LoginCredentials? params) =>
      (super.noSuchMethod(
            Invocation.method(#login, [params]),
            returnValue: _i11.Future<_i10.User>.value(
              _FakeUser_9(this, Invocation.method(#login, [params])),
            ),
          )
          as _i11.Future<_i10.User>);

  @override
  _i11.Future<_i10.User> register(_i48.RegisterCredentials? params) =>
      (super.noSuchMethod(
            Invocation.method(#register, [params]),
            returnValue: _i11.Future<_i10.User>.value(
              _FakeUser_9(this, Invocation.method(#register, [params])),
            ),
          )
          as _i11.Future<_i10.User>);

  @override
  _i11.Future<bool> isLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isLoggedIn, []),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<_i10.User?> getAuthenticatedUser() =>
      (super.noSuchMethod(
            Invocation.method(#getAuthenticatedUser, []),
            returnValue: _i11.Future<_i10.User?>.value(),
          )
          as _i11.Future<_i10.User?>);

  @override
  _i11.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i49.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i23.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_29(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i23.AuthRepository);

  @override
  _i11.Future<_i10.User> call(_i47.LoginCredentials? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i11.Future<_i10.User>.value(
              _FakeUser_9(this, Invocation.method(#call, [params])),
            ),
          )
          as _i11.Future<_i10.User>);
}

/// A class which mocks [RegisterUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterUseCase extends _i1.Mock implements _i50.RegisterUseCase {
  MockRegisterUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i23.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_29(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i23.AuthRepository);

  @override
  _i11.Future<_i10.User> call(_i48.RegisterCredentials? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i11.Future<_i10.User>.value(
              _FakeUser_9(this, Invocation.method(#call, [params])),
            ),
          )
          as _i11.Future<_i10.User>);
}

/// A class which mocks [LogoutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUseCase extends _i1.Mock implements _i51.LogoutUseCase {
  MockLogoutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i23.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_29(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i23.AuthRepository);

  @override
  _i11.Future<void> call(_i52.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [DeleteAccountUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteAccountUsecase extends _i1.Mock
    implements _i53.DeleteAccountUsecase {
  MockDeleteAccountUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i23.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_29(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i23.AuthRepository);

  @override
  _i11.Future<void> call(_i52.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [GetAuthenticatedUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAuthenticatedUserUseCase extends _i1.Mock
    implements _i54.GetAuthenticatedUserUseCase {
  MockGetAuthenticatedUserUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i23.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_29(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i23.AuthRepository);

  @override
  _i11.Future<_i10.User?> call(_i52.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i11.Future<_i10.User?>.value(),
          )
          as _i11.Future<_i10.User?>);
}

/// A class which mocks [EnvironmentLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockEnvironmentLocalDataSource extends _i1.Mock
    implements _i55.EnvironmentLocalDataSource {
  MockEnvironmentLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.APIConfig get currentApiConfig =>
      (super.noSuchMethod(
            Invocation.getter(#currentApiConfig),
            returnValue: _FakeAPIConfig_7(
              this,
              Invocation.getter(#currentApiConfig),
            ),
          )
          as _i9.APIConfig);

  @override
  _i26.Environment get currentEnvironment =>
      (super.noSuchMethod(
            Invocation.getter(#currentEnvironment),
            returnValue: _i26.Environment.dev,
          )
          as _i26.Environment);

  @override
  _i13.AuthConfig getAuthConfigForEnvironment(_i26.Environment? env) =>
      (super.noSuchMethod(
            Invocation.method(#getAuthConfigForEnvironment, [env]),
            returnValue: _FakeAuthConfig_17(
              this,
              Invocation.method(#getAuthConfigForEnvironment, [env]),
            ),
          )
          as _i13.AuthConfig);

  @override
  _i9.APIConfig getConfigForEnvironment(_i26.Environment? env) =>
      (super.noSuchMethod(
            Invocation.method(#getConfigForEnvironment, [env]),
            returnValue: _FakeAPIConfig_7(
              this,
              Invocation.method(#getConfigForEnvironment, [env]),
            ),
          )
          as _i9.APIConfig);

  @override
  _i11.Future<void> updateConfiguration(
    _i26.Environment? environment, {
    _i38.BaseUrlConfigModel? baseUrlConfig,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateConfiguration,
              [environment],
              {#baseUrlConfig: baseUrlConfig},
            ),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}
