import 'package:envied/envied.dart';

part 'env.g.dart';

/// Provides access to development environment variables.
///
/// This class is generated by the `envied` package and reads its values
/// from the `.env.dev` file at the root of the project.
/// The values are obfuscated at compile time for security.
@Envied(path: '.env.dev', name: 'EnvDev')
abstract class EnvDev {
  /// The base URL for the API in the development environment.
  @EnviedField(varName: 'BASE_URL', obfuscate: true)
  static final String baseUrl = _EnvDev.baseUrl;

  /// The API key for the development environment.
  @EnviedField(varName: 'API_KEY', obfuscate: true)
  static final String apiKey = _EnvDev.apiKey;
}

/// Provides access to production environment variables.
///
/// This class is generated by the `envied` package and reads its values
/// from the `.env.prod` file at the root of the project.
/// The values are obfuscated at compile time for security.
@Envied(path: '.env.prod', name: 'EnvProd')
abstract class EnvProd {
  /// The base URL for the API in the production environment.
  @EnviedField(varName: 'BASE_URL', obfuscate: true)
  static final String baseUrl = _EnvProd.baseUrl;

  /// The API key for the production environment.
  @EnviedField(varName: 'API_KEY', obfuscate: true)
  static final String apiKey = _EnvProd.apiKey;
}

/// Provides access to staging environment variables.
///
/// This class is generated by the `envied` package and reads its values
/// from the `.env.stage` file at the root of the project.
/// The values are obfuscated at compile time for security.
@Envied(path: '.env.stage', name: 'EnvStage')
abstract class EnvStage {
  /// The base URL for the API in the staging environment.
  @EnviedField(varName: 'BASE_URL', obfuscate: true)
  static final String baseUrl = _EnvStage.baseUrl;

  /// The API key for the staging environment.
  @EnviedField(varName: 'API_KEY', obfuscate: true)
  static final String apiKey = _EnvStage.apiKey;
}

/// Provides access to test environment variables.
///
/// This class is generated by the `envied` package and reads its values
/// from the `.env.test` file at the root of the project.
/// The values are obfuscated at compile time for security.
@Envied(path: '.env.test', name: 'EnvTest')
abstract class EnvTest {
  /// The base URL for the API in the test environment.
  @EnviedField(varName: 'BASE_URL', obfuscate: true)
  static final String baseUrl = _EnvTest.baseUrl;

  /// The API key for the test environment.
  @EnviedField(varName: 'API_KEY', obfuscate: true)
  static final String apiKey = _EnvTest.apiKey;
}
