import 'package:envied/envied.dart';

part 'env.g.dart';

/// Provides access to development environment variables.
///
/// This class is generated by the `envied` package and reads its values
/// from the `.env.dev` file at the root of the project.
/// The values are obfuscated at compile time for security.
@Envied(path: 'env/.env.dev', name: 'EnvDev')
abstract class EnvDev {
  /// The base URL for the API in the development environment.
  @EnviedField(varName: 'BASE_URL', obfuscate: true)
  static final String baseUrl = _EnvDev.baseUrl;

  /// The API key for the development environment.
  @EnviedField(varName: 'MOYASAR_PUBLISHABLE_KEY', obfuscate: true)
  static final String moyasarPublishableKey = _EnvDev.moyasarPublishableKey;
}



/// Provides access to production environment variables.
///
/// This class is generated by the `envied` package and reads its values
/// from the `.env.prod` file at the root of the project.
/// The values are obfuscated at compile time for security.
@Envied(path: 'env/.env.prod', name: 'EnvProd')
abstract class EnvProd {
  /// The base URL for the API in the production environment.
  @EnviedField(varName: 'BASE_URL', obfuscate: true)
  static final String baseUrl = _EnvProd.baseUrl;

  /// The moyasar publisher key for the development environment.
  @EnviedField(varName: 'MOYASAR_PUBLISHABLE_KEY', obfuscate: true)
  static final String moyasarPublishableKey = _EnvProd.moyasarPublishableKey;
}
